#ifndef TURBOACCELERATED_RAINBOW_TABLES_PATTERNENUM_H
#define TURBOACCELERATED_RAINBOW_TABLES_PATTERNENUM_H

const static unsigned int GEN_TABLE_PASS_LEN = 8;
const static unsigned int REDUCTION_PATTERNS_SIZE = 32;

enum REDUCTION_PATTERNS{
    REDUCTION_PATTERN0   =  0,
    REDUCTION_PATTERN1   =  1,
    REDUCTION_PATTERN2   =  2,
    REDUCTION_PATTERN3   =  3,
    REDUCTION_PATTERN4   =  4,
    REDUCTION_PATTERN5   =  5,
    REDUCTION_PATTERN6   =  6,
    REDUCTION_PATTERN7   =  7,
    REDUCTION_PATTERN8   =  8,
    REDUCTION_PATTERN9   =  9,
    REDUCTION_PATTERN10  =  10,
    REDUCTION_PATTERN11  =  11,
    REDUCTION_PATTERN12  =  12,
    REDUCTION_PATTERN13  =  13,
    REDUCTION_PATTERN14  =  14,
    REDUCTION_PATTERN15  =  15,
    REDUCTION_PATTERN16  =  16,
    REDUCTION_PATTERN17  =  17,
    REDUCTION_PATTERN18  =  18,
    REDUCTION_PATTERN19  =  19,
    REDUCTION_PATTERN20  =  20,
    REDUCTION_PATTERN21  =  21,
    REDUCTION_PATTERN22  =  22,
    REDUCTION_PATTERN23  =  23,
    REDUCTION_PATTERN24  =  24,
    REDUCTION_PATTERN25  =  25,
    REDUCTION_PATTERN26  =  26,
    REDUCTION_PATTERN27  =  27,
    REDUCTION_PATTERN28  =  28,
    REDUCTION_PATTERN29  =  29,
    REDUCTION_PATTERN30  =  30,
    REDUCTION_PATTERN31  =  31
};

const static char* const REDUCTION_PATTERN_VALUES[] = {
        [REDUCTION_PATTERN0]  = "0",
        [REDUCTION_PATTERN1]  = "1",
        [REDUCTION_PATTERN2]  = "2",
        [REDUCTION_PATTERN3]  = "3",
        [REDUCTION_PATTERN4]  = "4",
        [REDUCTION_PATTERN5]  = "5",
        [REDUCTION_PATTERN6]  = "6",
        [REDUCTION_PATTERN7]  = "7",
        [REDUCTION_PATTERN8]  = "8",
        [REDUCTION_PATTERN9]  = "9",
        [REDUCTION_PATTERN10] = "10",
        [REDUCTION_PATTERN11] = "11",
        [REDUCTION_PATTERN12] = "12",
        [REDUCTION_PATTERN13] = "13",
        [REDUCTION_PATTERN14] = "14",
        [REDUCTION_PATTERN15] = "15",
        [REDUCTION_PATTERN16] = "16",
        [REDUCTION_PATTERN17] = "17",
        [REDUCTION_PATTERN18] = "18",
        [REDUCTION_PATTERN19] = "19",
        [REDUCTION_PATTERN20] = "20",
        [REDUCTION_PATTERN21] = "21",
        [REDUCTION_PATTERN22] = "22",
        [REDUCTION_PATTERN23] = "23",
        [REDUCTION_PATTERN24] = "24",
        [REDUCTION_PATTERN25] = "25",
        [REDUCTION_PATTERN26] = "26",
        [REDUCTION_PATTERN27] = "27",
        [REDUCTION_PATTERN28] = "28",
        [REDUCTION_PATTERN29] = "29",
        [REDUCTION_PATTERN30] = "30",
        [REDUCTION_PATTERN31] = "31"
};

#endif //TURBOACCELERATED_RAINBOW_TABLES_PATTERNENUM_H
