#ifndef TURBOACCELERATED_RAINBOW_TABLES_REDUCTION_H
#define TURBOACCELERATED_RAINBOW_TABLES_REDUCTION_H

void reduce(const unsigned char* digest, char* output);

#endif //TURBOACCELERATED_RAINBOW_TABLES_REDUCTION_H
