#include <string.h>
#include "fileio.h"

#ifndef TURBOACCELERATED_RAINBOW_TABLES_TABLELOOKUP_H
#define TURBOACCELERATED_RAINBOW_TABLES_TABLELOOKUP_H

#define MAX_RAINBOW_TABLE_LINE_LEN                256

#endif //TURBOACCELERATED_RAINBOW_TABLES_TABLELOOKUP_H
